version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
build_script:
- ps: msbuild /t:restore,pack /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /verbosity:minimal
test_script:
- ps: dotnet test test\NLog.DiagnosticSource.Tests\NLog.DiagnosticSource.Tests.csproj
artifacts:
  - path: '**\NLog.*.nupkg'
  - path: '**\NLog.*.snupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 2iBH0sHibezU4otyUMZbykjuJwcmcM4WWm02vKYnR98GfdZVyz10P4FunVGTF39n
  on:
    branch: master
